# -*- coding: utf-8 -*-
"""20/02 IADAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Bm_80GcMR3N_PSZDOg9RgyWTm8AZF0lC
"""

import sqlite3

### Conectarse a la BD (o crearla en caso de que no exista) y asegurar que la conexión se cierra automáticamente...
# Usar 'with' statement para asegurar que la conexión se cierra correctamente al salir del bloque.
with sqlite3.connect('mi_base_de_datos.db') as conn:
    ### Crear un cursor - Atane a un apuntador que permite realizar las operaciones CRUD (Create, Retrieve, Update, Delete)...
    cur = conn.cursor()


    #### HEADER ####

    ### Buscar una tabla en la BD antes de crearla y eliminarla para evitar errores de ejecución y lógicos...
    cur.execute("DROP TABLE IF EXISTS DetalleEntrada")

    ### Crear una tabla con sus campos y sus tipos de dato, además de definir la llave primaria de la tabla (junto con el par de llaves foráneas)...
    cur.execute("CREATE TABLE DetalleEntrada (IdDetalleEntrada INTEGER, CantidadDetalleEntrada INTEGER, ValorTotalDetalleEntrada REAL, CodEntrada INTEGER, CodInsumo INTEGER, PRIMARY KEY(IdDetalleEntrada), FOREIGN KEY (CodEntrada) REFERENCES Entrada(IdEntrada), FOREIGN KEY(CodInsumo) REFERENCES INSUMO(IdInsumo))")

    ### Ingresar registros por separado en la tabla, acorde a la secuencia de los campos (Corresponde a la operación CRUD de creación de registros - Create)
    cur.execute("INSERT INTO DetalleEntrada (IdDetalleEntrada, CantidadDetalleEntrada, ValorTotalDetalleEntrada, CodEntrada, CodInsumo) VALUES (?, ?, ?, ?, ?)", (1, 12, 110.64, 1, 4))

    ### Ingresar un segundo registro en la tabla...
    cur.execute("INSERT INTO DetalleEntrada (IdDetalleEntrada, CantidadDetalleEntrada, ValorTotalDetalleEntrada, CodEntrada, CodInsumo) VALUES (?, ?, ?, ?, ?)", (2, 9, 68.22, 1, 1))

    ### Ingresar un tercer registro en la tabla...
    cur.execute("INSERT INTO DetalleEntrada (IdDetalleEntrada, CantidadDetalleEntrada, ValorTotalDetalleEntrada, CodEntrada, CodInsumo) VALUES (?, ?, ?, ?, ?)", (3, 5, 29.65, 2, 2))

    ### Ingresar un cuarto registro en la tabla...
    cur.execute("INSERT INTO DetalleEntrada (IdDetalleEntrada, CantidadDetalleEntrada, ValorTotalDetalleEntrada, CodEntrada, CodInsumo) VALUES (?, ?, ?, ?, ?)", (4, 20, 57.4, 3, 5))

    # Guardar los cambios en la base de datos.
    conn.commit()

    ### Mostrar un título para efectuar una consulta de datos...
    print("\nDetalle de la Entrada...")

    ### Consultar de manera general los registros de una tabla (Corresponde a la operación CRUD de consulta de registros - Retrieve)...
    cur.execute("SELECT * FROM DetalleEntrada")

    ### Recorrer el cursor que contiene la ejecución de la consulta y mostrar los registros uno a uno...
    for fila in cur:
        print(fila)

    #### FOOTER ####
    # cur.close() y conn.close() no son necesarios aquí, ya que el 'with' statement
    # se encarga de cerrar la conexión (y por ende el cursor asociado) al salir del bloque.

import sqlite3

# 1. Crear la conexión en la memoria de Colab (o un archivo .db)
conn = sqlite3.connect(':memory:') # Usamos :memory: para pruebas rápidas
cur = conn.cursor()

print("Carlos Fernando Forero Tellez")

# 2. Borrar la tabla si ya existe para evitar errores al re-ejecutar
cur.execute("DROP TABLE IF EXISTS DetalleEntrada")

# 3. Crear la tabla con la estructura necesaria
# El orden de las columnas es importante para que coincida con los INSERT de abajo
cur.execute("""
CREATE TABLE DetalleEntrada (
    IdDetalleEntrada INTEGER PRIMARY KEY,
    CantidadDetalleEntrada INTEGER,
    ValorTotalDetalleEntrada REAL,
    CodEntrada INTEGER,
    CodInsumo INTEGER
)
""")

# 4. Insertar los 5 registros exactos de tu captura de Excel
# Formato: (Id, Cantidad, ValorTotal, CodEntrada, CodInsumo)
datos = [
    (1, 12, 110.64, 1, 4), # Added CodInsumo = 4
    (2, 9, 68.22, 1, 1), # Added CodInsumo = 1
    (3, 5, 29.65, 2, 2), # Added CodInsumo = 2
    (4, 20, 57.4, 3, 5), # Added CodInsumo = 5
    (5, 10, 62.1, 3, 3)  # Added CodInsumo = 3
]

cur.executemany("""
INSERT INTO DetalleEntrada (IdDetalleEntrada, CantidadDetalleEntrada, ValorTotalDetalleEntrada, CodEntrada, CodInsumo)
VALUES (?, ?, ?, ?, ?)
""", datos)

# Guardar los cambios
conn.commit()

# 5. Consultar y mostrar los datos
print("\nDetalle de la Entrada :")
cur.execute("SELECT * FROM DetalleEntrada")

# Recorrer el cursor y mostrar las filas
for fila in cur:
    print(fila)

# 6. Cerrar conexiones
cur.close()
conn.close()

print("")