# -*- coding: utf-8 -*-
"""Base de datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kZGTZ4RKg3byfPzvlQ-MoVKHm5MwCkll
"""

!pip install -q requests pandas

import importlib.util, sys

# Cargar las funciones del modelo desde app.py
spec = importlib.util.spec_from_file_location("app", "app.py")

# Mock de streamlit/plotly para que no falle al importar
from unittest.mock import MagicMock
sys.modules['streamlit'] = MagicMock()
sys.modules['plotly'] = MagicMock()
sys.modules['plotly.graph_objects'] = MagicMock()

app = importlib.util.module_from_spec(spec)
spec.loader.exec_module(app)
print("✓ Motor cargado")

import json

with open("estado_2026-06-27.json") as f:
    estado = json.load(f)

jugados    = [p for p in estado["partidos"] if p.get("resultado_real")]
pendientes = [p for p in estado["partidos"] if not p.get("resultado_real")]

C1 = estado["modelo"]["capa1_confianza_global"]
GB = estado["modelo"]["capa3_sesgo_goleador"]
print(f"✓ Estado cargado — {len(jugados)} jugados, {len(pendientes)} pendientes")
print(f"  C1={C1}  GB={GB:+}")

from collections import defaultdict

por_fecha = defaultdict(list)
for p in pendientes:
    por_fecha[p["fecha"]].append(p)

for fecha in sorted(por_fecha.keys()):
    print(f"\n── {fecha.upper()} ──")
    for p in por_fecha[fecha]:
        w, x, l, marcador, pw, aj = app.predecir(p, estado)
        ea, eb = p["equipo_a"], p["equipo_b"]
        gan = ea if pw=="A" else eb if pw=="B" else "EMPATE"
        print(f"  G{p['grupo']} {ea} vs {eb} → {marcador} ({gan}) | {w}/{x}/{l}")

estado, nuevos, error = app.ingestar(estado)

if error:
    print(f"Error: {error}")
elif not nuevos:
    print("Sin resultados nuevos.")
else:
    print(f"✓ {len(nuevos)} resultado(s) nuevo(s):")
    for n in nuevos:
        p = n["partido"]
        print(f"  {p['equipo_a']} vs {p['equipo_b']} = {n['resultado_real']}")

from datetime import date

nombre = f"estado_{date.today()}.json"
with open(nombre, "w") as f:
    json.dump(estado, f, ensure_ascii=False, indent=2)

# Descargar al computador
from google.colab import files
files.download(nombre)
print(f"✓ Descargado: {nombre}")