# -*- coding: utf-8 -*-
"""diseño bd universidades.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GC82zLaaG5zVp7oriqRldFM_nXH3fTlZ
"""

from numpy import index_exp
#Construcción la tabla pais de la bd
import sqlite3
import pandas as pd


####header

coon = sqlite3.connect("BDUN.sqlite")
cur = coon.cursor()

#cargar en un dataframe el archivo preparado
datos = pd.read_csv("cwurDataPreparado.csv")
#print(datos)

##header
####_______TABLA PAIS______###

#Creacion tabla
cur.execute("DROP TABLE IF EXISTS Pais")
cur.execute("CREATE TABLE PAIS (IdPais INTEGRER, NombrePais TEXT UNIQUE, PRIMARY KEY(IdPais))")

indice = 0

for registroPais in datos.iterrows():
  index_value, column_values = registroPais
  array1 = column_values['country']
  cur.execute("INSERT OR IGNORE INTO Pais(IdPais, NombrePais) VALUES (?, ?)",
  ((indice + 1), array1))
  indice = cur.lastrowid
#query de insercion
coon.commit()
#################
#sentencia consulta general
cur.execute("SELECT * FROM Pais")

#presentar
print("\nConsulta general de la tabla Pais....\n")
for registro in cur:
  print(registro)
#footer
cur.close()
coon.close()




####footer