# -*- coding: utf-8 -*-
"""ejercicio tabla viaje.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OeqTPjVUCNfKOtWalH2k5CCPHbyLR1uI
"""

import sqlite3

# 1. Configuración de Base de Datos
DB_NAME = "BDF_Facturacion.db"
conexion = sqlite3.connect(DB_NAME)
cur = conexion.cursor()
cur.execute("PRAGMA foreign_keys = ON;")

def inicializar_base_de_datos():
    """Crea la estructura e inserta los datos según tu diagrama y diccionario."""
    cur.executescript("""
        DROP TABLE IF EXISTS DETALLE_FACTURA;
        DROP TABLE IF EXISTS FACTURA;
        DROP TABLE IF EXISTS PRODUCTO;
        DROP TABLE IF EXISTS CLIENTE;

        CREATE TABLE CLIENTE (
            ID_CLI INTEGER PRIMARY KEY AUTOINCREMENT,
            NOM_CLI TEXT,
            NIT_CLI TEXT,
            DIR_CLI TEXT,
            CIU_CLI TEXT,
            TEL_CLI TEXT
        );

        CREATE TABLE PRODUCTO (
            ID_PROD INTEGER PRIMARY KEY AUTOINCREMENT,
            NOM_PROD TEXT,
            PRE_UNIT REAL
        );

        CREATE TABLE FACTURA (
            ID_FAC INTEGER PRIMARY KEY AUTOINCREMENT,
            NUM_FAC TEXT,
            FEC_FAC TEXT,
            ID_CLI INTEGER,
            FOREIGN KEY(ID_CLI) REFERENCES CLIENTE(ID_CLI)
        );

        CREATE TABLE DETALLE_FACTURA (
            ID_DET INTEGER PRIMARY KEY AUTOINCREMENT,
            ID_FAC INTEGER,
            ID_PROD INTEGER,
            CANT INTEGER,
            PRE_VENT REAL,
            FOREIGN KEY(ID_FAC) REFERENCES FACTURA(ID_FAC),
            FOREIGN KEY(ID_PROD) REFERENCES PRODUCTO(ID_PROD)
        );

        -- Inserción de datos del dataset (Cliente de Bogotá)
        INSERT INTO CLIENTE (NOM_CLI, NIT_CLI, DIR_CLI, CIU_CLI, TEL_CLI)
        VALUES ('Fulano Detal', '12345678-9', 'Calle 1 #2-3', 'Bogotá', '123 4567');

        INSERT INTO PRODUCTO (NOM_PROD, PRE_UNIT) VALUES ('Pasajes Madrid Bogotá IR', 100.0);
        INSERT INTO PRODUCTO (NOM_PROD, PRE_UNIT) VALUES ('Reserva Hotel ABC 7 días', 300.0);

        INSERT INTO FACTURA (NUM_FAC, FEC_FAC, ID_CLI) VALUES ('00123', '01/01/2012', 1);

        INSERT INTO DETALLE_FACTURA (ID_FAC, ID_PROD, CANT, PRE_VENT) VALUES (1, 1, 4, 100.0);
        INSERT INTO DETALLE_FACTURA (ID_FAC, ID_PROD, CANT, PRE_VENT) VALUES (1, 2, 2, 300.0);
    """)
    conexion.commit()

# Ejecutar configuración inicial
inicializar_base_de_datos()

# --- BLOQUE DE SALIDA ---
print("=" * 50)
print("REALIZADO POR: CARLOS FORERO")
print("=" * 50 + "\n")

# CONSULTA 1: Detalle de clientes con todos sus datos
print(">>> CONSULTA 1: DETALLE COMPLETO DE CLIENTES")
query1 = "SELECT * FROM CLIENTE"
cur.execute(query1)
clientes = cur.fetchall()

for c in clientes:
    print(f"ID: {c[0]} | Nombre: {c[1]} | NIT: {c[2]}")
    print(f"Dirección: {c[3]} | Ciudad: {c[4]} | Teléfono: {c[5]}")
    print("-" * 50)


# CONSULTA 2: Mostrar factura solo de radicados en Bogotá
print("\n>>> CONSULTA 2: FACTURACIÓN CLIENTES BOGOTÁ")
query2 = """
    SELECT F.NUM_FAC, P.NOM_PROD, D.CANT, D.PRE_VENT, (D.CANT * D.PRE_VENT)
    FROM FACTURA F
    JOIN CLIENTE C ON F.ID_CLI = C.ID_CLI
    JOIN DETALLE_FACTURA D ON F.ID_FAC = D.ID_FAC
    JOIN PRODUCTO P ON D.ID_PROD = P.ID_PROD
    WHERE C.CIU_CLI = 'Bogotá';
"""
cur.execute(query2)
filas = cur.fetchall()

subtotal_bogota = 0
if filas:
    print(f"{'No. FAC':<8} | {'PRODUCTO':<25} | {'CANT':<4} | {'SUBTOTAL'}")
    for f in filas:
        print(f"{f[0]:<8} | {f[1]:<25} | {f[2]:<4} | ${f[4]}")
        subtotal_bogota += f[4]

    # Cálculos finales basados en la normalización (Atributos derivados)
    iva = subtotal_bogota * 0.16
    print("-" * 55)
    print(f"{' ' * 31} SUBTOTAL BOGOTÁ: ${subtotal_bogota}")
    print(f"{' ' * 31} IVA (16%):       ${iva}")
    print(f"{' ' * 31} TOTAL FINAL:     ${subtotal_bogota + iva}")
else:
    print("No existen facturas para clientes en Bogotá.")

conexion.close()

import sqlite3

# 1. CONFIGURACIÓN INICIAL DE BASE DE DATOS
# Usamos un solo nombre de archivo para toda la sesión
DB_NAME = "BDF_Facturacion.db"
conexion = sqlite3.connect(DB_NAME)
cur = conexion.cursor()

# Habilitar soporte de llaves foráneas para mantener relaciones 1:N
cur.execute("PRAGMA foreign_keys = ON;")

def inicializar_sistema():
    """Crea las tablas según el diccionario e inserta datos base."""
    cur.executescript("""
        -- Eliminar tablas existentes para asegurar estado limpio
        DROP TABLE IF EXISTS DETALLE_FACTURA;
        DROP TABLE IF EXISTS FACTURA;
        DROP TABLE IF EXISTS PRODUCTO;
        DROP TABLE IF EXISTS CLIENTE;

        -- Tabla CLIENTE (Basada en Diccionario)
        CREATE TABLE CLIENTE (
            ID_CLI INTEGER PRIMARY KEY AUTOINCREMENT,
            NOM_CLI TEXT NOT NULL,
            NIT_CLI TEXT UNIQUE NOT NULL,
            DIR_CLI TEXT,
            CIU_CLI TEXT,
            TEL_CLI TEXT
        );

        -- Tabla PRODUCTO (Basada en Diccionario)
        CREATE TABLE PRODUCTO (
            ID_PROD INTEGER PRIMARY KEY AUTOINCREMENT,
            NOM_PROD TEXT NOT NULL,
            PRE_UNIT REAL NOT NULL
        );

        -- Tabla FACTURA (Cabecera 1:N con Cliente)
        CREATE TABLE FACTURA (
            ID_FAC INTEGER PRIMARY KEY AUTOINCREMENT,
            NUM_FAC TEXT NOT NULL,
            FEC_FAC TEXT NOT NULL,
            ID_CLI INTEGER,
            FOREIGN KEY(ID_CLI) REFERENCES CLIENTE(ID_CLI)
        );

        -- Tabla DETALLE_FACTURA (Normalizada según imagen DetalleFactura)
        CREATE TABLE DETALLE_FACTURA (
            IdDetalleFactura INTEGER PRIMARY KEY AUTOINCREMENT,
            CantidadDetalleFactura INTEGER NOT NULL,
            ValorTotalDetalleFactura REAL NOT NULL,
            CodFactura INTEGER,
            CodProducto INTEGER,
            FOREIGN KEY(CodFactura) REFERENCES FACTURA(ID_FAC),
            FOREIGN KEY(CodProducto) REFERENCES PRODUCTO(ID_PROD)
        );

        -- --- INSERCIÓN DE DATOS DE PRUEBA (Basado en Dataset 00123) ---

        -- 1. Insertar Cliente (Radicado en Bogotá)
        INSERT INTO CLIENTE (NOM_CLI, NIT_CLI, DIR_CLI, CIU_CLI, TEL_CLI)
        VALUES ('Fulano Detal', '12345678-9', 'Calle 1 #2-3', 'Bogotá', '123 4567');

        -- 2. Insertar Productos Maestros
        INSERT INTO PRODUCTO (NOM_PROD, PRE_UNIT) VALUES ('Pasajes Madrid Bogotá IR', 100.0);
        INSERT INTO PRODUCTO (NOM_PROD, PRE_UNIT) VALUES ('Reserva Hotel ABC 7 días', 300.0);

        -- 3. Insertar Cabecera de Factura
        INSERT INTO FACTURA (NUM_FAC, FEC_FAC, ID_CLI) VALUES ('00123', '01/01/2012', 1);

        -- 4. Insertar Detalles (Usando tus IDs exactos del dataset)
        -- IdDetalleFactura, Cantidad, ValorTotal, CodFactura, CodProducto
        INSERT INTO DETALLE_FACTURA (IdDetalleFactura, CantidadDetalleFactura, ValorTotalDetalleFactura, CodFactura, CodProducto)
        VALUES (1, 4, 400.0, 1, 1);

        INSERT INTO DETALLE_FACTURA (IdDetalleFactura, CantidadDetalleFactura, ValorTotalDetalleFactura, CodFactura, CodProducto)
        VALUES (2, 2, 600.0, 1, 2);
    """)
    conexion.commit()

# Ejecutar la inicialización
inicializar_sistema()


# --- BLOQUE DE IMPRESIÓN DEL DISEÑO DE FACTURA ---

print("=" * 60)
print("REALIZADO POR: CARLOS FORERO")
print("=" * 60 + "\n")

# 1. Consulta Compleja (JOIN) para traer todos los datos necesarios
# Reconstruimos la factura 00123 cruzando Cliente, Factura, Detalles y Productos
query_join = """
    SELECT
        F.NUM_FAC, F.FEC_FAC,
        C.NOM_CLI, C.NIT_CLI, C.DIR_CLI, C.CIU_CLI, C.TEL_CLI,
        P.NOM_PROD, D.CantidadDetalleFactura, D.ValorTotalDetalleFactura
    FROM FACTURA F
    JOIN CLIENTE C ON F.ID_CLI = C.ID_CLI
    JOIN DETALLE_FACTURA D ON F.ID_FAC = D.CodFactura
    JOIN PRODUCTO P ON D.CodProducto = P.ID_PROD
    WHERE F.NUM_FAC = '00123';
"""
cur.execute(query_join)
detalles = cur.fetchall()

if detalles:
    # Extraer datos de cabecera del primer registro
    info_cabecera = detalles[0]
    num_factura = info_cabecera[0]
    fecha_factura = info_cabecera[1]
    nombre_cliente = info_cabecera[2]
    nit_cliente = info_cabecera[3]
    direccion = info_cabecera[4]
    ciudad = info_cabecera[5]
    telefono = info_cabecera[6]

    # --- DISEÑO VISUAL DE LA FACTURA ---
    print("+" + "-" * 58 + "+")
    print(f"| {'INFORMACION DE MI NEGOCIO...':^56} |")
    print("+" + "-" * 58 + "+")
    print(f"|{' ':^58}|")

    # Cabecera de Cliente y Factura (Alineación izquierda/derecha)
    col1_w = 30 # Ancho columna izquierda
    print(f"| {('CLIENTE: ' + nombre_cliente):<{col1_w}}  {('FACTURA No. ' + num_factura):>24} |")
    print(f"| {('NIT: ' + nit_cliente):<{col1_w}}  {('FECHA: ' + fecha_factura):>24} |")
    print(f"| {('DIRECCION: ' + direccion):<{col1_w}}{' ':>26} |")
    print(f"| {('CIUDAD: ' + ciudad):<{col1_w}}{' ':>26} |")
    print(f"| {('TELEFONO: ' + telefono):<{col1_w}}{' ':>26} |")

    print(f"|{' ':^58}|")

    # Tabla de Detalle de Factura
    print(f"| {'DETALLE DE LA FACTURA':^56} |")
    print("+" + "-" * 58 + "+")

    # Encabezados de tabla de detalle
    # CANTIDAD (8) | PRODUCTO (25) | V/R TOTAL (12)
    encabezado_tabla = f"| {'CANTIDAD':^8} | {'PRODUCTO':^25} | {'V/R TOTAL':^12} |"
    print(encabezado_tabla)
    print("+" + "-" * 58 + "+")

    subtotal_general = 0
    for fila in detalles:
        producto_nom = fila[7]
        cantidad = fila[8]
        valor_total = fila[9]

        # F-string con alineación específica:
        # Cantidad centrada (:^8)
        # Producto izquierda (:<25)
        # Valor derecha con signo $ (:>12)
        print(f"| {cantidad:^8} | {producto_nom:<25} | {'$' + str(int(valor_total)):>12} |")
        subtotal_general += valor_total

    print("+" + "-" * 58 + "+")

    # Sección de Totales (Alineados a la derecha)
    # iva calculado (atributo derivado)
    iva = subtotal_general * 0.16
    grand_total = subtotal_general + iva

    # Usamos f-string para alinear los totales a la derecha
    # Ancho del texto es 40 para que coincida con el borde derecho
    print(f"|{' ':^14} {'SubTotal':^25}{' ':^2} | {'$' + str(int(subtotal_general)):>12} |")
    print(f"|{' ':^14} {'Iva':^25}{' ':^2} | {'$' + str(int(iva)):>12} |")
    print(f"|{' ':^14} {'Gran Total':^25}{' ':^2} | {'$' + str(int(grand_total)):>12} |")
    print("+" + "-" * 58 + "+")

else:
    print("No se encontró la Factura No. 00123.")

# Cerrar conexión
conexion.close()